# -*- coding: utf-8 -*-
"""Human action.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WmL6ZKW5faK8vxiWd3noVb-Qj8R3qyuU
"""

from django.shortcuts import render
from django.http import StreamingHttpResponse
import cv2
import mediapipe as mp
import numpy as np
import pyautogui

# Initialize MediaPipe Pose
mp_pose = mp.solutions.pose
pose = mp_pose.Pose()
mp_drawing = mp.solutions.drawing_utils
drawing_utils = mp.solutions.drawing_utils

mp_hands = mp.solutions.hands
hands = mp_hands.Hands()

play_pause_state = False  # False means paused, True means playing
prev_dist = 0
threshold = 50
change_delay = 5
frame_count = 0
def detect_action(landmarks):
    if not landmarks:
        return "Unknown"

    left_wrist = landmarks[mp_pose.PoseLandmark.LEFT_WRIST.value]
    left_shoulder = landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value]
    right_wrist = landmarks[mp_pose.PoseLandmark.RIGHT_WRIST.value]
    right_shoulder = landmarks[mp_pose.PoseLandmark.RIGHT_SHOULDER.value]
    left_elbow = landmarks[mp_pose.PoseLandmark.LEFT_ELBOW.value]
    right_elbow = landmarks[mp_pose.PoseLandmark.RIGHT_ELBOW.value]
    left_hip = landmarks[mp_pose.PoseLandmark.LEFT_HIP.value]
    right_hip = landmarks[mp_pose.PoseLandmark.RIGHT_HIP.value]
    left_knee = landmarks[mp_pose.PoseLandmark.LEFT_KNEE.value]
    right_knee = landmarks[mp_pose.PoseLandmark.RIGHT_KNEE.value]

    torso_vertical = abs(left_shoulder.x - left_hip.x) < 0.1 and abs(right_shoulder.x - right_hip.x) < 0.1
    legs_straight = abs(left_knee.y - left_hip.y) > 0.3 and abs(right_knee.y - right_hip.y) > 0.3
    arms_neutral = left_wrist.y > left_shoulder.y and right_wrist.y > right_shoulder.y

    if torso_vertical and legs_straight and arms_neutral:
        return "Standing Pose"
    if left_wrist.y < left_elbow.y - 0.1 and left_wrist.y < left_shoulder.y - 0.1:
        return "Left Arm Stretching"
    if right_wrist.y < right_elbow.y - 0.1 and right_wrist.y < right_shoulder.y - 0.1:
        return "Right Hand Stretching"
    if left_wrist.y < left_shoulder.y:
        return "Left Hand Raised"
    if right_wrist.y < right_shoulder.y:
        return "Right Hand Raised"
    if (abs(left_wrist.y - left_shoulder.y) < 0.05 and abs(right_wrist.y - right_shoulder.y) < 0.05 and
        left_wrist.x < left_shoulder.x and right_wrist.x > right_shoulder.x):
        return "T-Pose"

    return "Unknown"

def process_frame(frame):
    img_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    pose_result = pose.process(img_rgb)
    action = "Unknown"

    if pose_result.pose_landmarks:
        landmarks = pose_result.pose_landmarks.landmark
        action = detect_action(landmarks)
        mp_drawing.draw_landmarks(frame, pose_result.pose_landmarks, mp_pose.POSE_CONNECTIONS)

    cv2.putText(frame, f'Action: {action}', (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1,(0, 0, 0), 2)
    return frame

def video_feed():
    cap = cv2.VideoCapture(0)

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        frame = process_frame(frame)
        _, buffer = cv2.imencode('.jpg', frame)
        frame_bytes = buffer.tobytes()

        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame_bytes + b'\r\n')

    cap.release()

def video_stream(request):
    return StreamingHttpResponse(video_feed(), content_type="multipart/x-mixed-replace;boundary=frame")

def index(request):
    return render(request, 'index.html')

def action(request):
    return render(request, 'action.html')
def detect_gesture(hand_landmarks):
    if not hand_landmarks:
        return "Unknown Gesture"

    thumb_tip = hand_landmarks[mp_hands.HandLandmark.THUMB_TIP]
    index_tip = hand_landmarks[mp_hands.HandLandmark.INDEX_FINGER_TIP]
    middle_tip = hand_landmarks[mp_hands.HandLandmark.MIDDLE_FINGER_TIP]
    ring_tip = hand_landmarks[mp_hands.HandLandmark.RING_FINGER_TIP]
    pinky_tip = hand_landmarks[mp_hands.HandLandmark.PINKY_TIP]

    thumb_ip = hand_landmarks[mp_hands.HandLandmark.THUMB_IP]
    index_dip = hand_landmarks[mp_hands.HandLandmark.INDEX_FINGER_DIP]
    middle_dip = hand_landmarks[mp_hands.HandLandmark.MIDDLE_FINGER_DIP]
    ring_dip = hand_landmarks[mp_hands.HandLandmark.RING_FINGER_DIP]
    pinky_dip = hand_landmarks[mp_hands.HandLandmark.PINKY_DIP]

    # Calculate distances
    thumb_index_dist = np.linalg.norm(np.array([thumb_tip.x, thumb_tip.y]) - np.array([index_tip.x, index_tip.y]))
    thumb_middle_dist = np.linalg.norm(np.array([thumb_tip.x, thumb_tip.y]) - np.array([middle_tip.x, middle_tip.y]))

    # Define gesture conditions
    if thumb_tip.y < thumb_ip.y and index_tip.y > index_dip.y:
        return "Thumbs Up"
    if thumb_index_dist < 0.05 and thumb_middle_dist > 0.1:
        return "OK"
    if (thumb_tip.y > thumb_ip.y and index_tip.y > index_dip.y and
        middle_tip.y > middle_dip.y and ring_tip.y > ring_dip.y and
        pinky_tip.y > pinky_dip.y):
        return "Fist"
    if (thumb_tip.y < thumb_ip.y and index_tip.y < index_dip.y and
        middle_tip.y < middle_dip.y and ring_tip.y < ring_dip.y and
        pinky_tip.y < pinky_dip.y):
        return "Good/Nice"
    if (index_tip.y < index_dip.y and middle_tip.y < middle_dip.y and
        ring_tip.y > ring_dip.y and pinky_tip.y > pinky_dip.y):
        return "Peace Sign"

    return "Unknown Gesture"

# Function to process gesture frames
def process_gesture_frame(frame):
    img_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    hand_result = hands.process(img_rgb)
    gesture = "Unknown Gesture"

    if hand_result.multi_hand_landmarks:
        for hand_landmarks in hand_result.multi_hand_landmarks:
            gesture = detect_gesture(hand_landmarks.landmark)
            mp_drawing.draw_landmarks(frame, hand_landmarks, mp_hands.HAND_CONNECTIONS)

    cv2.putText(frame, f'Gesture: {gesture}', (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 0), 2)
    return frame

# Function to stream gesture video
def gesture_feed():
    cap = cv2.VideoCapture(0)

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        frame = process_gesture_frame(frame)
        _, buffer = cv2.imencode('.jpg', frame)
        frame_bytes = buffer.tobytes()

        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame_bytes + b'\r\n')

    cap.release()

# Function to return gesture video as streaming response
def gesture_stream(request):
    return StreamingHttpResponse(gesture_feed(), content_type="multipart/x-mixed-replace;boundary=frame")


def gesture(request):
    return render(request, 'gesture.html')

def detect_gestures():
    """Captures webcam frames, processes hand gestures, and sends video stream."""
    global play_pause_state, prev_dist, frame_count

    cap = cv2.VideoCapture(0)  # Open webcam
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        frame = cv2.flip(frame, 1)
        rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        output = hands.process(rgb_frame)

        if output.multi_hand_landmarks and output.multi_handedness:
            for hand_landmarks, hand_label in zip(output.multi_hand_landmarks, output.multi_handedness):
                drawing_utils.draw_landmarks(frame, hand_landmarks, mp_hands.HAND_CONNECTIONS)
                landmarks = hand_landmarks.landmark
                hand_type = hand_label.classification[0].label  # 'Left' or 'Right'

                # Right Hand: Play/Pause
                if hand_type == 'Right':
                    index_finger_up = landmarks[8].y < landmarks[7].y
                    middle_finger_up = landmarks[12].y < landmarks[11].y

                    if index_finger_up and not middle_finger_up:  # Pause
                        if play_pause_state:
                            pyautogui.press("playpause")
                            play_pause_state = False

                    elif index_finger_up and middle_finger_up:  # Play
                        if not play_pause_state:
                            pyautogui.press("playpause")
                            play_pause_state = True

                # Left Hand: Volume Control
                elif hand_type == 'Left':
                    x1, y1 = int(landmarks[4].x * frame.shape[1]), int(landmarks[4].y * frame.shape[0])  # Thumb
                    x2, y2 = int(landmarks[8].x * frame.shape[1]), int(landmarks[8].y * frame.shape[0])  # Index Finger

                    dist = ((x2 - x1) ** 2 + (y2 - y1) ** 2) ** 0.5 // 4
                    cv2.line(frame, (x1, y1), (x2, y2), (0, 255, 0), 5)

                    frame_count += 1
                    if frame_count > change_delay:
                        if dist > threshold and dist > prev_dist:
                            pyautogui.press("volumeup")
                        elif dist < threshold and dist < prev_dist:
                            pyautogui.press("volumedown")
                        frame_count = 0
                        prev_dist = dist

        # Convert frame to JPEG and yield as response
        _, buffer = cv2.imencode('.jpg', frame)
        frame_bytes = buffer.tobytes()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame_bytes + b'\r\n')

    cap.release()
def video_feeds(request):
    """Returns a streaming HTTP response for video feed."""
    return StreamingHttpResponse(detect_gestures(), content_type='multipart/x-mixed-replace; boundary=frame')
def handpose(request):
    return render(request, 'handpose.html')